### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by adhikjoshi** [Ugness/MeBT#1]
Hey, really cool paper.

Can you update readme with more examples?
Is it FOSS?
Expected date of release?

**Comment by Ugness** [comment]
Thanks for your interest.
You may access more results on the project page. (https://sites.google.com/view/mebt-cvpr2023/home)
The readme will be updated with the code release.
Yes, it is FOSS, and I'll release the code within 2 weeks. I'll send you an e-mail when I release the code.

**Comment by Ugness** [comment]
Dear @adhikjoshi, I apologize for the late code release than expected. Now I released the code and the things to reproduce my result. Feel free to use them for your research & project. Thank you.
