### ISSUE TITLE
Where is the code? 

### ISSUE THREAD

**Issue by spacewalkingninja** [Ugness/MeBT#2]
Hello, I taskj you to ASAP release
Full code,
Most advanced Models & Checkpoints you got (actually, even the not so good ones u got, better release them!)
Documentantion
You got 6 hours before I get home to start programming. Release them before this @Ugness !
Thanks!
Any questions drop them here.

**Comment by Ugness** [comment]
Dear @spacewalkingninja, I apologize for the late reply and code release. Now I released the full code, checkpoints, and also documentation of my project. Thank you for being so interested.
