### ISSUE TITLE
Can you provide the detailed training consumption?

### ISSUE THREAD

**Issue by EricLina** [Ugness/MeBT#3]
Can you provide FLOPs for training? Or approximate training time with the  corresponding number of GPUs.

**Comment by Ugness** [comment]
We didn't measure FLOPS for training.
In the case of 128-frame training, training on SkyTimelapse took 12hrs with 4 A100 GPUs, and training on Taichi and UCF-101 took about 2 weeks with 8 A100 GPUs.

**Comment by EricLina** [comment]
thanks
